version: '3.4'

services:
  reactcaculator:
    image: reactcaculator
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5173:5173
